# ---- Defaults for 4 agents hunting 1 stag and 1 hare in a 10x10 environment

env: "stag_hunt"

env_args:
    agent_obs: [2, 2]
    capture_terminal: True
    capture_conditions: [0, 0]  # number of free fields available to stag and hare to be captured
    episode_limit: 100
    intersection_global_view: False
    intersection_unknown: False
    mountain_slope: 0.5 # Probability that an "up" action will not be executed (stag_hunt = 0.0)
    mountain_spawn: True # Whether prey spawns in their preferred habitat (True) or randomly (False)
    mountain_agent_row: 1 # the row in which the agents are spawned. Negative values spawn agents randomly.
    n_agents: 4
    n_hare: 1
    n_stags: 1
    observe_walls: False
    observe_ids: False
    observe_one_hot: False
    p_stags_rest: 0.0
    p_hare_rest: 0.0
    reward_hare: 5
    reward_stag: 10
    reward_collision: 0.0
    reward_time: 0.0
    toroidal: False
    world_shape: [10, 10]

t_max: 2000000
