# --- Defaults for SC2, only positive rewards, max cumulative reward=20 ---

env: sc2

env_args:
  map_name: "3m_3m" # 3 marines by default
  difficulty: "3"
  heuristic: False
  move_amount: 2
  reward_death_value: 10
  reward_negative_scale: 0.5
  reward_only_positive: True
  reward_scale: True
  reward_scale_rate: 20
  reward_win: 200
  state_last_action: True
  step_mul: 8
  obs_instead_of_state: False
  obs_own_health: True
  obs_all_health: True
  continuing_episode: False
  restrict_actions: True
  game_version: "3.16.1"

test_nepisode: 32
test_interval: 10000
log_interval: 2000
runner_log_interval: 2000
learner_log_interval: 2000
t_max: 2000000
